# Generated by Django 3.2.12 on 2025-03-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
